# Generated by Django 4.2 on 2023-04-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('last_name', models.TextField()),
                ('age', models.IntegerField()),
                ('email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DatosCliente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('direccion', models.TextField()),
                ('edad', models.IntegerField()),
                ('profesion', models.TextField()),
            ],
        ),
    ]
